server:
  port: 8080
#  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  redis:
    host: localhost
    port: 6379
    database: 0
    cache:
      redis:
        time-to-live: 1800000
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      indent_output: true
      fail_on_empty_beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.60.174.122:3306/diancan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: diancan
#    password: 123456
    url: jdbc:mysql://localhost:3306/diancan?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    mybatis-plus:
      configuration:
        map-underscore-to-camel-case: true
